spring:
  application:
    name: app
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: test
    group:
      local:
      test:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}

  lock-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    hikari:
      pool-name: lock-pool
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
